### ISSUE TITLE
Visualizations

### ISSUE THREAD

**Issue by sperng** [jchou8/centertable-final-project#7]
1. Map of US with consumption shown and slider that changes the year

- Also add options to switch to production and expenditures (have all three with a radio widget to switch between them)

**Comment by jphchou** [comment]
2. Line graph of each different energy source's production over time with widgets that can filter/group the lines

**Comment by feliciatd** [comment]
3.  Bar chart of all the states' total expenditures along with widgets that can show the expenditures 
 by state or by energy type.

**Comment by andrewroger424** [comment]
Stacked bar  graph with each states energy consumption. Clean stacked on top of not clean. Slider that changes the year

**Comment by andrewroger424** [comment]
Pie chart with energy type expenditure. Widget option to filter between states, and slider to filter year.
